version: "3.8"

services:
  backend:
    build:
      context: ./backend  # 🔹 Indique le dossier du backend
      dockerfile: Dockerfile  # 🔹 Spécifie le fichier Dockerfile du backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend  # 🔹 Indique le dossier du frontend
      dockerfile: Dockerfile  # 🔹 Spécifie le fichier Dockerfile du frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
